Fix client generic context
replit/crosis pull request #53
Opened 2020-09-18 21:42 UTC by masad-frost

Why
===
Right now context is passed to each `open` and `openChannel` calls. Typing like that works for most cases but you don't get any real type check guarantees. As it's unlikely for the shape of the context to change between `open` calls, we set the context on the client and let 

What changed
============
Ctx is now passed as a generic to `Client<{ username: string }>`. All calls now implicitly get the context.
Renamed generic from `D` to `Ctx`

2020-09-18 21:53 UTC, turbio requested changes

2020-09-18 21:53 UTC, turbio commented on src/client.ts
> +      // @ts-ignore context is not relevant until we call the `open` function
eek, this feels wrong since it's not a consequence of the environment. IMO tslint isn't really appropriate like this in new code :shrug:

2020-09-18 22:03 UTC, masad-frost commented on src/client.ts
> +      // @ts-ignore context is not relevant until we call the `open` function
Can you expand on what you mean? There's no way to deal with this type of generic otherwise, the only alternative is what we had or maybe I'm missing something. What we had is an in-cohesive context type that doesn't give any static typing guarantees.

2020-09-18 22:46 UTC, masad-frost commented on src/client.ts
> +      // @ts-ignore context is not relevant until we call the `open` function
@sergeichestakov can I get your input here?

Happy to close the PR but this is more useful than using `any` all over the place and in-cohesive context

2020-09-18 23:11 UTC, sergeichestakov commented on src/client.ts
> +      // @ts-ignore context is not relevant until we call the `open` function
yeah it's not great. any way we can make `context` an optional param? probably should be since we don't require the user to pass it in

2020-09-19 00:12 UTC, masad-frost commented on src/client.ts
> +      // @ts-ignore context is not relevant until we call the `open` function
Made it optional. Gonna try it out later and see how it feels.

2020-09-21 21:58 UTC, masad-frost commented on src/client.ts
> +      // @ts-ignore context is not relevant until we call the `open` function
Isn't really usable like this, doesn't inherit the actual type from the client, assumes it could always be falsy. Gonna try another approach

2020-09-21 22:11 UTC, masad-frost commented
Updated the description

2020-09-21 22:33 UTC, sergeichestakov approved these changes

2020-09-21 22:34 UTC, merged